#define SUN_SPEED 5
#define MOON_SPEED (6 * SUN_SPEED)

#define LIGHT_COLOR_DAY "#FFFFFF"
#define LIGHT_COLOR_DAWN "#FFD580"
#define LIGHT_COLOR_DUSK "#FFA07A"
#define LIGHT_COLOR_NIGHT "#111111"
#define LIGHT_INTENSITY_DAY 5
#define LIGHT_INTENSITY_NIGHT 0
//epic otimizaçao
#define TURFS_UPDATE_PERCENT 0.05